import React, { createContext, useState, useEffect, useContext } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

// SABİT ÇEVİRİLER
const translations = {
  tr: {
    agenda: "Gündem",
    featured: "Öne Çıkanlar",
    seeAll: "Tümünü Gör",
    announcements: "Duyurular & Haberler",
    events: "Etkinlik Takvimi",
    campusLife: "Kampüste Hayat",
    dining: "Günün Menüsü",
    bonAppetit: "Afiyet Olsun",
    menu: "Menü",
    studentLogin: "Öğrenci Girişi",
    academicCalendar: "Akademik Takvim",
    contact: "İletişim",
    logout: "Çıkış Yap",
    readMore: "Devamını Oku",
    details: "Detaylar",
    notLoggedIn: "Giriş Yapılmadı",
    login: "Giriş Yap",
    library: "Kütüphane",
    contactGuide: "İletişim & Rehber",
    calendarGeneral: "Genel Takvim",
    calendarMedicine: "Tıp Fakültesi",
    calendarVet: "Veteriner Fakültesi",
    calendarEn: "Academic Calendar (EN)",
    universityName: "ÜNİVERSİTESİ",
    addressTitle: "Adres",
    phoneTitle: "Santral",
    emailTitle: "E-Posta",
    webTitle: "Web Sitesi",
    copyright: "© 2025 Kastamonu Üniversitesi Bilgi İşlem Daire Başkanlığı",
    gallery: "Galeri",
    attendance: "Yoklama",
    joinWithCode: "Kod ile Katıl",
    joinWithQR: "QR ile Katıl",
    attendanceCodeTitle: "Yoklama Kodu",
    attendanceCodeDesc: "Dersi veren öğretim üyesinin paylaştığı yoklama kodunu aşağıya giriniz.",
    codePlaceholder: "Örn: 123456",
    joinButton: "Yoklamaya Katıl",
    codeSuccessMessage: "Kod ile yoklamaya katılındı:",
    cameraPermissionRequest: "Kamera izni isteniyor...",
    noCameraPermission: "Kamera izni yok",
    scanQROverlay: "QR Kodu okutun",
    qrScannedTitle: "QR Kod Okundu!",
    myCourses: "Derslerim",
    courseName: "Ders Adı",
    midterm: "Vize",
    final: "Final",
    average: "Ortalama",
    grade: "Harf",
    status: "Durum",
    passed: "Geçti",
    failed: "Kaldı",
    attendanceOperations: "Yoklama İşlemleri",
    instructorLogin: "Akademisyen Girişi",
    myIdCard: "Kimlik Kartım",
    guestUser: "Misafir Kullanıcı",
    welcome: "Hoş Geldiniz",
    mobileApp:"Mobil Uygulama",
    ok:"Tamam",
    idCard: {
    title: "Dijital Kimlik",
    uniName: "KASTAMONU ÜNİVERSİTESİ",
    cardType: "KİMLİK KARTI",
    studentNo: "Öğrenci No",
    tcNo: "T.C. Kimlik No",
    faculty: "Fakülte / Bölüm",
    active: "Aktif Öğrenci",
    scan: "Doğrulama için okutunuz",
    cardId: "Kart No",
    loading: "Kart bilgileri yükleniyor...",
    error: "Kart bilgisi bulunamadı.",
    retry: "Tekrar Dene",
  },
  sideMenu: {
    academicTitle: "AKADEMİK İŞLEMLER",
    attendance: "Yoklama ve Dersler",
    joinQr: "QR ile Katıl",
    joinCode: "Kod ile Katıl",
    createCourse: "Ders Aç (Eğitmen)",
    instructorOps: "Yoklama İşlemleri",
    successTitle: "Başarılı",
    errorTitle: "Hata",
    sessionExpired: "Oturum süreniz dolmuş, lütfen tekrar giriş yapın.",
    serverError: "Sunucuya bağlanılamadı.",
    successMessage: "✅ Yoklamaya başarıyla katıldınız!",
    invalidCode: "❌ Kod geçersiz veya süresi dolmuş.",
    ok: "Tamam",
    retry: "Tekrar Dene",
    exit: "Çık",
    schedule: "Ders Programı",
    courseOperations: "Ders İşlemleri",
    myCourses: "Derslerim",
    absenteeism: "Devamsızlık Bilgisi"
  },
    categories: {
      all: "Tümü",
      student: "Öğrenci Duyuruları",
      academic: "Birim Haberleri",
      admin: "Üniversite Duyuruları",
      general: "Üniversite Haberleri"
    },
    qr: {
    overlay: "Karekodu okutunuz",
    permissionRequest: "Kamera izni gerekiyor",
    noPermission: "Kamera izni yok",
    successTitle: "Başarılı",
    errorTitle: "Hata",
    sessionExpired: "Oturum süreniz dolmuş, lütfen tekrar giriş yapın.",
    serverError: "Sunucuya bağlanılamadı.",
    successMessage: "✅ Yoklamaya başarıyla katıldınız!",
    invalidCode: "❌ QR Kod geçersiz veya süresi dolmuş.",
    ok: "Tamam",
    retry: "Tekrar Dene",
    exit: "Çık"
  },
  courseSchedule: {
    title: "Ders Programı",
    days: ["Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma", "Cumartesi", "Pazar"],
    noLesson: "Bu gün için ders bulunmamaktadır.",
    loading: "Ders programı yükleniyor...",
    error: "Ders programı alınamadı.",
    classroom: "Derslik",
    lecturer: "Öğretim Elemanı"
  },
  absenteeism: {
    title: "Devamsızlık Bilgisi",
    modalTitle: "Devamsızlık Detayı",
    total: "TOPLAM",
    attended: "KATILDI",
    absent: "YOK",
    hour: "Saat",
    rate: "Devam Oranı",
    rule: "Ders geçme alt limiti %70 olarak baz alınmıştır.",
    weekly: "Haftalık Döküm",
    present: "Var",
    absentStatus: "Yok",
    lessonHour: "Ders Saati",
    noData: "Kayıt bulunamadı.",
    loading: "Dersler yükleniyor...",
    noCourse: "Ders kaydı bulunamadı.",
    calculating: "Veriler alınıyor...",
    error: "Hata oluştu."
  },
  instructor:{
    title: "Yoklama Listesi",
    save: "Kaydet",
    saved: "Kaydedildi",
    error: "Hata",
    blockMode: "Blok Modu",
    hourMode: "Saat Bazlı Mod",
    searchPlaceholder: "Öğrenci Ara...",
    present: "GELEN",
    absent: "GELMEYEN",
    total: "MEVCUT",
    hoursLabel: "DERS SAATLERİ",
    yes: "VAR",
    no: "YOK",
    noStudent: "Öğrenci bulunamadı.",
    search: "ARA"
  },
  attendanceTitle: "Yoklama",
  courseHours: "Ders Saatleri",
  block: "Blok",
  createQR: "QR Oluştur",
  createCode: "Kod Oluştur",
  qrTab: "QR Kod",
  codeTab: "Şifre",
  studentList: "Öğrenci Listesi",
  searchPlaceholder: "İsim veya numara ile ara...",
  save: "Kaydet",
  saved: "Kaydedildi",
  savedMessage: "öğrencinin yoklaması kaydedildi.",
  info: "Bilgi",
  noChange: "Herhangi bir değişiklik yapılmadı.",
  loadingList: "Liste yükleniyor...",
  studentNotFound: "Öğrenci bulunamadı.",
  presentFull: "GELDİ (Tam Gün)",
  absentFull: "YOK (Tam Gün)",
  joinInfo: "Öğrenciler {0} derse katılabilir.",
  courseManagement:"Ders Yönetimi",
  noActiveLesson: "Aktif Ders Yok",
  noActiveLessonDesc: "Şu an yoklama başlatabileceğiniz bir ders saati içerisinde değilsiniz.",
  checkingLessons: "Dersler kontrol ediliyor...",
  attendanceCanStart: "YOKLAMA BAŞLATILABİLİR",
  refresh: "Yenile",
  manageAttendance: "Yoklama Yönet",
  lessonsLoadError: "Dersler yüklenemedi.",
  qrModule: "QR Modülü",
  startingQR: "{0} için QR başlatılıyor...",
  codeModule: "Kod Modülü",
  generatingCode: "{0} için kod üretiliyor...",
  active: "Aktif",
  attendanceManagement: "Yoklama Yönetimi",
  error:"Hata",
    },
  en: {
    agenda: "Agenda",
    featured: "Featured",
    seeAll: "See All",
    announcements: "Announcements & News",
    events: "Event Calendar",
    campusLife: "Campus Life",
    dining: "Daily Menu",
    bonAppetit: "Bon Appétit",
    menu: "Menu",
    studentLogin: "Student Login",
    academicCalendar: "Academic Calendar",
    contact: "Contact",
    logout: "Log Out",
    readMore: "Read More",
    details: "Details",
    notLoggedIn: "Not Logged In",
    login: "Login",
    library: "Library",
    contactGuide: "Contact & Guide",
    calendarGeneral: "General Calendar",
    calendarMedicine: "Faculty of Medicine",
    calendarVet: "Faculty of Veterinary Medicine",
    calendarEn: "Academic Calendar (EN)",
    universityName: "UNIVERSITY",
    addressTitle: "Address",
    phoneTitle: "Switchboard",
    emailTitle: "E-Mail",
    webTitle: "Website",
    copyright: "© 2025 Kastamonu University IT Department",
    gallery: "Gallery",
    attendance: "Attendance",
    joinWithCode: "Join via Code",
    joinWithQR: "Join via QR",
    attendanceCodeTitle: "Attendance Code",
    attendanceCodeDesc: "Enter the attendance code shared by the instructor below.",
    codePlaceholder: "Ex: 123456",
    joinButton: "Join Attendance",
    codeSuccessMessage: "Joined attendance via code:",
    cameraPermissionRequest: "Requesting camera permission...",
    noCameraPermission: "No camera permission",
    scanQROverlay: "Scan QR Code",
    qrScannedTitle: "QR Code Scanned!",
    myCourses: "My Courses",
    courseName: "Course Name",
    midterm: "Midterm",
    final: "Final",
    average: "Average",
    grade: "Letter",
    status: "Status",
    passed: "Passed",
    failed: "Failed",
    attendanceOperations: "Attendance Operations",
    instructorLogin: "Instructor Login",
    myIdCard: "My ID Card",
    guestUser: "Guest User",
    welcome: "Welcome",
    mobileApp:"Mobile App",
    ok:"Ok",
    idCard: {
    title: "Digital ID",
    uniName: "KASTAMONU UNIVERSITY",
    cardType: "ID CARD",
    studentNo: "Student No",
    tcNo: "TR ID No",
    faculty: "Faculty / Dept",
    active: "Active Student",
    scan: "Scan for verification",
    cardId: "Card No",
    loading: "Loading card information...",
    error: "No card information found.",
    retry: "Retry",
  },
  sideMenu: {
    academicTitle: "ACADEMIC OPERATIONS",
    attendance: "Attendance & Courses",
    joinQr: "Join via QR",
    joinCode: "Join via Code",
    createCourse: "Create Course (Instructor)",
    instructorOps: "Attendance Operations",
    successTitle: "Success",
    errorTitle: "Error",
    sessionExpired: "Session expired, please login again.",
    serverError: "Could not connect to server.",
    successMessage: "✅ You have successfully joined!",
    invalidCode: "❌ Invalid or expired Code.",
    ok: "OK",
    retry: "Retry",
    exit: "Exit",
    schedule: "Course Schedule",
    courseOperations: "Course Operations",
    myCourses: "My Courses",
    absenteeism: "Absenteeism Info",
  },
    categories: {
      all: "All",
      student: "Student Announcements",
      academic: "Unit News",
      admin: "University Announcements",
      general: "University News"
    },
    qr: {
    overlay: "Scan the QR code",
    permissionRequest: "Camera permission required",
    noPermission: "No camera permission",
    successTitle: "Success",
    errorTitle: "Error",
    sessionExpired: "Session expired, please login again.",
    serverError: "Could not connect to server.",
    successMessage: "✅ You have successfully joined!",
    invalidCode: "❌ Invalid or expired QR Code.",
    ok: "OK",
    retry: "Retry",
    exit: "Exit"
  },
  courseSchedule: {
    title: "Course Schedule",
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    noLesson: "No lessons for this day.",
    loading: "Loading schedule...",
    error: "Could not fetch schedule.",
    classroom: "Classroom",
    lecturer: "Lecturer"
  },
  absenteeism: {
    title: "Attendance Info",
    modalTitle: "Attendance Details",
    total: "TOTAL",
    attended: "PRESENT",
    absent: "ABSENT",
    hour: "Hrs",
    rate: "Attendance Rate",
    rule: "Based on 70% attendance requirement.",
    weekly: "Weekly Breakdown",
    present: "Present",
    absentStatus: "Absent",
    lessonHour: "Lesson Hour",
    noData: "No records found.",
    loading: "Loading courses...",
    noCourse: "No course records found.",
    calculating: "Fetching data...",
    error: "An error occurred."
  },
  instructor:{
    title: "Attendance List",
    save: "Save",
    saved: "Saved",
    error: "Error",
    blockMode: "Block Mode",
    hourMode: "Hour Mode",
    searchPlaceholder: "Search Student...",
    present: "PRESENT",
    absent: "ABSENT",
    total: "TOTAL",
    hoursLabel: "CLASS HOURS",
    yes: "YES",
    no: "NO",
    noStudent: "No student found.",
    search: "SEARCH"
  },
  attendanceTitle: "Attendance",
  courseHours: "Course Hours",
  block: "Block",
  createQR: "Create QR",
  createCode: "Create Code",
  qrTab: "QR Code",
  codeTab: "Password",
  studentList: "Student List",
  searchPlaceholder: "Search by name or number...",
  save: "Save",
  saved: "Saved",
  savedMessage: "students attendance saved.",
  info: "Info",
  noChange: "No changes made.",
  loadingList: "Loading list...",
  studentNotFound: "Student not found.",
  presentFull: "PRESENT (Full Day)",
  absentFull: "ABSENT (Full Day)",
  joinInfo: "Students can join the class {0}.",
  courseManagement:"Course Menagement",
  noActiveLesson: "No Active Lesson",
  noActiveLessonDesc: "You are not currently within a class hour to start attendance.",
  checkingLessons: "Checking lessons...",
  attendanceCanStart: "ATTENDANCE AVAILABLE",
  refresh: "Refresh",
  manageAttendance: "Manage Attendance",
  lessonsLoadError: "Lessons could not be loaded.",
  qrModule: "QR Module",
  startingQR: "Starting QR for {0}...",
  codeModule: "Code Module",
  generatingCode: "Generating code for {0}...",
  active: "Active",
  attendanceManagement: "Attendance Management",
  error:"Error"
  }
};

type Language = 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations['tr']) => any; 
  dictionary: typeof translations['tr'];
}
// ---------------------------

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLangState] = useState<Language>('tr');

  useEffect(() => {
    AsyncStorage.getItem('appLanguage').then((savedLang) => {
      if (savedLang === 'tr' || savedLang === 'en') {
        setLangState(savedLang);
      }
    });
  }, []);

  const setLanguage = async (lang: Language) => {
    setLangState(lang);
    await AsyncStorage.setItem('appLanguage', lang);
  };

  const dictionary = translations[language];
  const t = (key: keyof typeof translations['tr']) => dictionary[key];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dictionary }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within a LanguageProvider");
  return context;
};